spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/megalab
    username: mamatkadyruulu
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 100MB
app:
  security:
    token:
      secret: youcannothackusbecausewehavestrongsecretkey
      expires-after-days: 1
  folder-path: src/main/resources/images/
server:
  error:
    include-message: always